# Generated by Django 4.2.2 on 2023-07-04 10:17

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AlterModelManagers(
            name='addbook',
            managers=[
                ('book_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
